site_name: SignLink
site_description: Breaking Barriers with Fingerspelling Technology
site_author: Rajtilak Bhattacharjee
site_url: https://rajtilakjee.github.io/SignLink/

repo_url: https://github.com/rajtilakjee/SignLink

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - search.suggest
    - navigation.sections
    - navigation.top
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rajtilakjee/SignLink
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/rajtilakjee
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/rajtilak/
    - icon: fontawesome/brands/discord
      link: https://discordapp.com/users/969666251536347146

plugins:
  - search:
      lang: en

nav:
  - Home: index.md
  - Contributing Guide: contributing.md
